# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr/ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr/ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rocr/ocr.proto\x12\x03ocr\"\x1f\n\nOCRRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"4\n\x0bOCRResponse\x12\x16\n\x0e\x65xtracted_text\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2?\n\nOCRService\x12\x31\n\nProcessPdf\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponse\"\x00\x42\x07Z\x05./ocrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr.ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./ocr'
  _globals['_OCRREQUEST']._serialized_start=22
  _globals['_OCRREQUEST']._serialized_end=53
  _globals['_OCRRESPONSE']._serialized_start=55
  _globals['_OCRRESPONSE']._serialized_end=107
  _globals['_OCRSERVICE']._serialized_start=109
  _globals['_OCRSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
