// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
