// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {stats} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetSystemStats():Promise<stats.SystemStats>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartScan():Promise<void>;

export function StopScan():Promise<void>;
